- name: install Apache with mod_ssl
  yum:
    name: mod_ssl
    state: present
  become: yes

- name: configure Apache
  template:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf
  become: yes
  notify:
   - restart httpd

- name: start the httpd service
  service:
    name: httpd
    state: started
    enabled: yes
  become: yes
